[package]
name = "waveless_commons"
edition = "2024"

[dependencies]
rustyrosetta = { workspace = true, features = ["all"] }
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
