[alias]
test-all = "test --all-features -- --nocapture"

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=/Applications/Xcode-16.4.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld",
]

[target.wasm32-unknown-unknown]
rustflags = [
    "--cfg",
    "getrandom_backend=\"wasm_js\"",
    "--cfg",
    "erase_components",
]
