[alias]
run-frontend = "run --package waveless_frontend --bin waveless_frontend --all-features"
run-executor = "run --package waveless_executor --bin waveless_executor --all-features"
test-all = "test --all-features -- --nocapture"
doc-all = "doc --workspace --no-deps"

[build]
rustc-wrapper = "/Users/nv0skar/.cargo/bin/sccache"
rustdocflags = ["-Zunstable-options", "--enable-index-page"]

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=/Applications/Xcode-16.4.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld",
]

[target.wasm32-unknown-unknown]
rustflags = [
    "--cfg",
    "getrandom_backend=\"wasm_js\"",
    "--cfg",
    "erase_components",
]
